"""add published_at to notice

Revision ID: 534657f22f86
Revises: 004
Create Date: 2026-02-18 03:52:40.274816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534657f22f86'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('colleges_external_id_key', 'colleges', type_='unique')
    op.add_column('notices', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('notices_college_id_fkey', 'notices', type_='foreignkey')
    op.create_foreign_key(None, 'notices', 'colleges', ['college_id'], ['id'])
    op.drop_constraint('user_calendar_events_notice_id_fkey', 'user_calendar_events', type_='foreignkey')
    op.drop_constraint('user_calendar_events_user_id_fkey', 'user_calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'user_calendar_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_calendar_events', 'notices', ['notice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'user_calendar_events', type_='foreignkey')
    op.create_foreign_key('user_calendar_events_user_id_fkey', 'user_calendar_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_calendar_events_notice_id_fkey', 'user_calendar_events', 'notices', ['notice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.create_foreign_key('notices_college_id_fkey', 'notices', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notices', 'published_at')
    op.create_unique_constraint('colleges_external_id_key', 'colleges', ['external_id'])
    # ### end Alembic commands ###
